/*
  # Create kenig_rates table

  1. New Tables
    - `kenig_rates`
      - `id` (bigint, primary key, auto-increment)
      - `sell` (numeric) - Sell rate
      - `buy` (numeric) - Buy rate
      - `updated_at` (timestamptz) - Last update timestamp
      - `source` (text) - Source of the rate
      - `base` (text) - Base currency
      - `quote` (text) - Quote currency
      - `last_price` (numeric) - Last price

  2. Indexes
    - Unique index on (source, base, quote)
    - Unique index on source where base and quote are null

  3. Initial Data
    - Insert sample data for various cryptocurrencies
*/

-- Create the kenig_rates table
CREATE TABLE IF NOT EXISTS kenig_rates (
  id bigint generated by default as identity not null,
  sell numeric null,
  buy numeric null,
  updated_at timestamp with time zone null,
  source text null,
  base text null,
  quote text null,
  last_price numeric null,
  constraint kenig_rates_pkey primary key (id)
);

-- Create unique indexes
CREATE UNIQUE INDEX IF NOT EXISTS kenig_rates_uq ON public.kenig_rates 
  USING btree (source, base, quote) TABLESPACE pg_default;

CREATE UNIQUE INDEX IF NOT EXISTS kenig_rates_uq_source_null ON public.kenig_rates 
  USING btree (source) TABLESPACE pg_default
  WHERE ((base IS NULL) AND (quote IS NULL));

-- Enable Row Level Security
ALTER TABLE kenig_rates ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access to kenig_rates"
  ON kenig_rates
  FOR SELECT
  TO public
  USING (true);

-- Create policy for authenticated users to insert/update rates
CREATE POLICY "Allow authenticated users to insert kenig_rates"
  ON kenig_rates
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update kenig_rates"
  ON kenig_rates
  FOR UPDATE
  TO authenticated
  USING (true);

-- Insert initial sample data with various cryptocurrencies
INSERT INTO kenig_rates (source, base, quote, sell, buy, updated_at) VALUES
  ('kenig', 'USDT', 'RUB', 95.50, 94.80, now()),
  ('kenig', 'BTC', 'RUB', 2800000.00, 2750000.00, now()),
  ('kenig', 'ETH', 'RUB', 180000.00, 175000.00, now()),
  ('kenig', 'BNB', 'RUB', 25000.00, 24500.00, now()),
  ('kenig', 'USDC', 'RUB', 95.30, 94.70, now()),
  ('kenig', 'ADA', 'RUB', 35.00, 34.00, now()),
  ('kenig', 'DOT', 'RUB', 450.00, 440.00, now()),
  ('kenig', 'SOL', 'RUB', 8500.00, 8300.00, now()),
  ('kenig', 'MATIC', 'RUB', 45.00, 44.00, now()),
  ('kenig', 'AVAX', 'RUB', 2200.00, 2150.00, now()),
  ('kenig', 'XRP', 'RUB', 38.00, 37.00, now()),
  ('kenig', 'DOGE', 'RUB', 8.50, 8.30, now()),
  ('kenig', 'SHIB', 'RUB', 0.0018, 0.0017, now()),
  ('kenig', 'LTC', 'RUB', 5800.00, 5700.00, now()),
  ('kenig', 'LINK', 'RUB', 950.00, 930.00, now()),
  ('kenig', 'UNI', 'RUB', 520.00, 510.00, now()),
  ('kenig', 'ATOM', 'RUB', 650.00, 635.00, now()),
  ('kenig', 'XLM', 'RUB', 28.00, 27.50, now()),
  ('kenig', 'TRX', 'RUB', 7.50, 7.30, now()),
  ('kenig', 'FIL', 'RUB', 320.00, 315.00, now()),
  ('kenig', 'NEAR', 'RUB', 280.00, 275.00, now()),
  ('bestchange', 'USDT', 'RUB', 95.30, 94.90, now()),
  ('energo', 'USDT', 'RUB', 95.20, 94.70, now());

-- Verify the data was inserted correctly
SELECT 
  'Table created successfully with ' || COUNT(*) || ' records' as status
FROM kenig_rates;

-- Show the inserted data to confirm everything is working
SELECT 
  source,
  base,
  quote,
  sell,
  buy,
  updated_at
FROM kenig_rates 
ORDER BY source, base;