/*
  # Create kenig_rates table for exchange rate management

  This migration creates the kenig_rates table that stores exchange rates from multiple sources
  (kenig, bestchange, energo, etc.) with comprehensive fields for managing exchange operations.

  1. New Tables
    - `kenig_rates`
      - `id` (bigint, primary key, auto-increment) - Unique identifier
      - `source` (text) - Source of the rate (kenig, bestchange, energo, etc.)
      - `base` (text) - Base currency (e.g., USDT, BTC, ETH)
      - `quote` (text) - Quote currency (e.g., RUB, USD, EUR)
      - `sell` (numeric) - Sell rate (how much quote currency you get for 1 base currency)
      - `buy` (numeric) - Buy rate (how much quote currency you pay for 1 base currency)
      - `rate` (numeric) - General rate field
      - `min_amount` (numeric) - Minimum exchange amount
      - `max_amount` (numeric) - Maximum exchange amount
      - `reserve` (numeric) - Available reserve amount
      - `operational_mode` (text) - Operation mode (auto, manual, semi-auto)
      - `working_hours` (jsonb) - Working hours configuration
      - `is_active` (boolean) - Whether the exchange direction is active
      - `conditions` (text) - Special conditions and requirements
      - `exchange_source` (text) - Additional source information
      - `last_price` (numeric) - Last known price
      - `updated_at` (timestamptz) - Last update timestamp
      - `created_at` (timestamptz) - Record creation timestamp

  2. Indexes
    - Unique index on (source, base, quote) for preventing duplicates
    - Index on (source, base, quote, updated_at) for efficient queries
    - Index on updated_at for time-based queries
    - Index on is_active for filtering active rates

  3. Security
    - Enable RLS on `kenig_rates` table
    - Add policy for public read access (exchange rates are public)
    - Add policies for authenticated users to insert/update/delete rates

  4. Initial Data
    - Insert sample data for various cryptocurrencies against RUB
*/

-- Create the kenig_rates table with all necessary columns
CREATE TABLE IF NOT EXISTS kenig_rates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL DEFAULT 'kenig',
  base text NULL,
  quote text NULL,
  sell numeric NULL,
  buy numeric NULL,
  rate numeric NULL,
  min_amount numeric NULL DEFAULT 0,
  max_amount numeric NULL DEFAULT 0,
  reserve numeric NULL DEFAULT 0,
  operational_mode text NULL DEFAULT 'auto',
  working_hours jsonb NULL,
  is_active boolean NULL DEFAULT true,
  conditions text NULL,
  exchange_source text NULL,
  last_price numeric NULL,
  updated_at timestamptz NULL DEFAULT now(),
  created_at timestamptz NULL DEFAULT now()
);

-- Create unique index to prevent duplicate rate entries
CREATE UNIQUE INDEX IF NOT EXISTS kenig_rates_uq 
  ON kenig_rates (source, base, quote);

-- Create index for efficient queries on source, base, quote, and updated_at
CREATE INDEX IF NOT EXISTS idx_kenig_rates_source_base_quote_updated 
  ON kenig_rates(source, base, quote, updated_at DESC);

-- Create index for time-based queries
CREATE INDEX IF NOT EXISTS idx_kenig_rates_updated_at 
  ON kenig_rates(updated_at DESC);

-- Create index for filtering active rates
CREATE INDEX IF NOT EXISTS idx_kenig_rates_is_active 
  ON kenig_rates(is_active) WHERE is_active = true;

-- Enable Row Level Security
ALTER TABLE kenig_rates ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access (exchange rates are public information)
CREATE POLICY "Allow public read access to kenig_rates"
  ON kenig_rates
  FOR SELECT
  TO public
  USING (true);

-- Create policy for authenticated users to insert rates
CREATE POLICY "Allow authenticated users to insert kenig_rates"
  ON kenig_rates
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Create policy for authenticated users to update rates
CREATE POLICY "Allow authenticated users to update kenig_rates"
  ON kenig_rates
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Create policy for authenticated users to delete rates
CREATE POLICY "Allow authenticated users to delete kenig_rates"
  ON kenig_rates
  FOR DELETE
  TO authenticated
  USING (true);

-- Insert initial sample data for kenig source
INSERT INTO kenig_rates (source, base, quote, sell, buy, min_amount, max_amount, reserve, operational_mode, is_active, conditions, updated_at) VALUES
  ('kenig', 'USDT', 'RUB', 95.50, 94.80, 100, 1000000, 50000, 'auto', true, 'TRC20, без верификации', now()),
  ('kenig', 'BTC', 'RUB', 2800000.00, 2750000.00, 0.001, 10, 5, 'auto', true, 'Bitcoin основная сеть', now()),
  ('kenig', 'ETH', 'RUB', 180000.00, 175000.00, 0.01, 100, 50, 'auto', true, 'Ethereum ERC20', now()),
  ('kenig', 'BNB', 'RUB', 25000.00, 24500.00, 0.1, 1000, 100, 'auto', true, 'BNB Smart Chain', now()),
  ('kenig', 'USDC', 'RUB', 95.30, 94.70, 100, 1000000, 30000, 'auto', true, 'ERC20, требуется верификация', now()),
  ('kenig', 'RUB', 'USDT', 0.0106, 0.0105, 10000, 10000000, 100000, 'auto', true, 'Сбербанк, Т-Банк, СБП', now())
ON CONFLICT (source, base, quote) 
DO UPDATE SET 
  sell = EXCLUDED.sell,
  buy = EXCLUDED.buy,
  min_amount = EXCLUDED.min_amount,
  max_amount = EXCLUDED.max_amount,
  reserve = EXCLUDED.reserve,
  operational_mode = EXCLUDED.operational_mode,
  is_active = EXCLUDED.is_active,
  conditions = EXCLUDED.conditions,
  updated_at = EXCLUDED.updated_at;

-- Insert sample data for other sources
INSERT INTO kenig_rates (source, base, quote, sell, buy, min_amount, max_amount, reserve, operational_mode, is_active, updated_at) VALUES
  ('bestchange', 'USDT', 'RUB', 95.30, 94.90, 100, 500000, 100000, 'manual', true, now()),
  ('energo', 'USDT', 'RUB', 95.20, 94.70, 100, 500000, 75000, 'semi-auto', true, now())
ON CONFLICT (source, base, quote) 
DO UPDATE SET 
  sell = EXCLUDED.sell,
  buy = EXCLUDED.buy,
  min_amount = EXCLUDED.min_amount,
  max_amount = EXCLUDED.max_amount,
  reserve = EXCLUDED.reserve,
  operational_mode = EXCLUDED.operational_mode,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

-- Verify the table was created and data inserted
SELECT 
  'kenig_rates table created successfully with ' || COUNT(*) || ' records' as status
FROM kenig_rates
WHERE base IS NOT NULL AND quote IS NOT NULL;